# Generated by Django 6.0.5 on 2026-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
