# Generated by Django 6.0.5 on 2026-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_app', '0003_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
